# title: "Introduction to Applied Machine Learning"
# author: John J. Curtin, PhD
project:
  output-dir: _slides
  render:
    - 001_overview.qmd
    - 002_exploratory_data_analysis.qmd
    - 003_regression.qmd
    - 004_classification.qmd
    - 005_resampling.qmd
    - 006_regularization.qmd
    - 008_advanced_performance_metrics.qmd
    - 009_model_comparisons.qmd
    - 010_random_forest.qmd
    - 011_neural_networks.qmd
    - 012_nlp.qmd
    - 013_applications.qmd
    - 014_ethics.qmd
toc: false
bibliography: refs.bib
css: slides.css
format: 
  revealjs:
    scrollable: true
callout-icon: false
execute:
  echo: true