toc: false
bibliography: refs.bib
css: slides_teaching.css
format: 
  revealjs:
    logo: uwlogo.png
    scrollable: true
    chalkboard: true
    slide-number: true
    show-slide-number: all 
    html-math-method: mathjax
    auto-stretch: false
callout-icon: false
callout-appearance: simple
execute:
  echo: true
