project:
  type: book
  output-dir: docs

execute:
  echo: true
  warning: true
  message: true

toc: true
toc-depth: 3
bibliography: refs.bib
css: style.css

book:
  title: "Introduction to Applied Machine Learning"
  author: John J. Curtin, PhD
  site-url: https://github.io/jjcurtin/book_iaml
  repo-url: https://github.com/jjcurtin/book_iaml
  repo-branch: main
  repo-actions: [edit]
  sharing: [facebook, linkedin]
  page-navigation: true
  reader-mode: true
  chapters:
    - index.qmd
    - 001_overview.qmd
    - 002_exploratory_data_analysis.qmd
    - 003_regression.qmd
    - 004_classification.qmd
    - 005_resampling.qmd
    - 006_regularization.qmd
    - 007_midterm.qmd
    - 008_advanced_performance_metrics.qmd
    - 009_model_comparisons.qmd
    - 010_random_forest.qmd
    - 011_neural_networks.qmd
    - 012_nlp.qmd
    - 013_applications.qmd
    - 014_ethics.qmd
    - 015_final.qmd
    - part: Appendices
      chapters:
        - app_terminology.qmd
        - app_dummy_coding.qmd
        - app_model_performance_simulations.qmd
        - app_shap.qmd
        - app_bootstrapping.qmd
        - app_test.qmd
callout-icon: false
