project:
  type: book

execute:
  echo: true
  warning: true
  message: true
  freeze: auto

toc: true
toc-depth: 3
bibliography: refs.bib
css: book.css
callout-icon: false
code-fold: show

book:
  title: "Introduction to Applied Machine Learning"
  author: John J. Curtin, PhD
  site-url: https://github.io/jjcurtin/book_iaml
  repo-url: https://github.com/jjcurtin/book_iaml
  repo-branch: main
  repo-actions: [edit]
  page-navigation: true
  reader-mode: true
  chapters:
    - index.qmd
    - course_materials.qmd
    - l01_overview.qmd
